name: new_sistem_informasi_smanda
description: "A new Flutter project."
publish_to: "none"
version: 1.2.0+11

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  add_2_calendar: ^3.0.1
  barcode_widget: ^2.0.4
  cached_network_image: ^3.4.1
  cloud_firestore: ^5.6.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  encrypt: ^5.0.3
  flutter_gen: ^5.11.0
  flutter_calendar_carousel: ^2.5.4
  file_picker: ^8.0.7
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  firebase_messaging: ^15.2.1
  firebase_storage: ^12.4.0
  flutter_bloc: ^9.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_svg: ^2.0.17
  get_it: ^7.7.0
  http: ^1.6.0
  image_picker: ^1.2.0
  hydrated_bloc: ^10.0.0
  intl: ^0.19.0
  lottie: ^3.1.3
  mobile_scanner: ^6.0.6
  mime: ^2.0.0
  onesignal_flutter: ^5.3.0
  path_provider: ^2.1.4
  path: ^1.9.0
  rename: ^3.0.2
  shimmer: ^3.0.0
  shared_preferences: ^2.5.1
  smooth_page_indicator: ^1.2.0+3
  stacked_listview: ^1.0.4
  url_launcher: ^6.3.2

dev_dependencies:
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.11.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/lotties/

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Black.ttf
          weight: 900
        - asset: assets/fonts/Satoshi-Bold.ttf
          weight: 600
        - asset: assets/fonts/Satoshi-Light.ttf
          weight: 500
        - asset: assets/fonts/Satoshi-Medium.ttf
          weight: 400
        - asset: assets/fonts/Satoshi-Regular.ttf
          weight: 300
